---
- name: Automated deployment of Cloud-1 infrastructure
  hosts: all
  become: yes

  vars:
    project_dir: /opt/cloud1

  roles:
    - role: docker
    - role: setup
    - role: ssl
    - role: wordpress